### PR TITLE
Replace `lz4c` with `lz4`

### PR DESCRIPTION
**Pull request by thevar1able**
Fixes https://github.com/alunduil/zfs-replicate/issues/349

### CODE REVIEW

**Review by alunduil — APPROVED** [review]
That looks as easy as I expected, would you mind adding a Changelog line for this change? If not, I'll get to that this weekend and publish a new release.

**Comment by thevar1able** [comment]
Sure.

**Comment by thevar1able** [comment]
Changelog seems to be just PR titles between the tags, should I change something in the repo or just add more description to the PR?

**Comment by alunduil** [comment]
The changelog does follow the pull request titles mostly but not always. I'll update that as I'm preparing the release this weekend. Thanks again for this submission!

**Pull request merged**
